<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim Todo</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-12 pt-5">

            <table class="table table-striped" id="todos">
                <tr>
                    <th>Task</th>
                    <th></th>
                    <th></th>
                </tr>
                <?php
                foreach ($todos as $todo){
                    ?>
                    <tr>
                        <td><?= $todo->done ? '<s>'.$todo->task.'</s>' : $todo->task; ?></td>
                        <td>
                            <form action="update" method="post">
                                <input name="id" type="hidden" value="<?= $todo->_id; ?>">
                                <button type="submit" class="btn btn-success">Done</button>
                            </form>
                        </td>
                        <td>
                            <form action="delete" method="post">
                                <input name="id" type="hidden" value="<?= $todo->_id; ?>">
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                    <?php
                }
                ?>
            </table>

            <form action="create" method="post" enctype="application/x-www-form-urlencoded">
                <textarea class="form-control" name="task" placeholder="Write your todo here..."></textarea>
                <button class="btn btn-success mt-3" type="submit">Create</button>
            </form>
        </div>
    </div>
</div>
</body>
</html>
